// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingBasketService.Persistence;

namespace ShoppingBasketService.Persistence.Migrations
{
    [DbContext(typeof(ShoppingBasketContext))]
    partial class ShoppingBasketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingBasketService.Domain.DomainModel.ShoppingBasketDomainModel.Basket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Basket");
                });

            modelBuilder.Entity("ShoppingBasketService.Domain.DomainModel.ShoppingBasketDomainModel.Entities.BasketLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasketId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TicketAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketLine");
                });

            modelBuilder.Entity("ShoppingBasketService.Domain.DomainModel.ShoppingBasketDomainModel.Entities.BasketLine", b =>
                {
                    b.HasOne("ShoppingBasketService.Domain.DomainModel.ShoppingBasketDomainModel.Basket", null)
                        .WithMany("BasketLines")
                        .HasForeignKey("BasketId");
                });

            modelBuilder.Entity("ShoppingBasketService.Domain.DomainModel.ShoppingBasketDomainModel.Basket", b =>
                {
                    b.Navigation("BasketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
